server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
   gateway:
    discovery:
     locator:
       enabled: true
    routes:
     - id: customer-service-config
       uri: lb://customer-service-config
       predicates:
        - Path=/customers/**
       
