server:
  port: 8081

spring:
  cloud:
    config:
      enable: true
      server:
        git:
          uri: https://github.com/Snayderstone/TestDef.git
          skipSslValidation: true
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
          searchPaths: config-service-data
        defaultLabel: Desarrollo

  security:
    user:
      name: admin
      password: admin